// SPDX-License-Identifier: MIT
#pragma once

#include <filesystem>
#include <string>
#include <vector>

#if defined(CNA_EXAMPLES_HAS_XACT_FILEGEN)
#  include "XactFileGen.hpp"
#endif

namespace CnaExamples::Demos::Audio::XactDemos {

// XACT needs three real binary files -- a global settings file (.xgs), a wave
// bank (.xwb) and a sound bank (.xsb) -- and CNA reads that format without ever
// writing it. They cannot be generated by ffmpeg the way every other asset in
// this app is, and no XACT authoring tool exists on Linux.
//
// ../cnanext already solved this for its own demo_xact program with a dependency-
// free generator. cmake/ExamplesHelpers.cmake puts that header on the include
// path; it is NOT copied into this repository, because it is Ms-PL and this
// repo is MIT. Compiling against it is no different from linking CNA itself.
//
// Without ../cnanext the demos still build and say so, which is the whole reason
// for the CNA_EXAMPLES_HAS_XACT_FILEGEN guard.

inline constexpr bool kXactGeneratorAvailable =
#if defined(CNA_EXAMPLES_HAS_XACT_FILEGEN)
    true;
#else
    false;
#endif

// Written to a temp directory, not into Content/: these are generated build
// products, and a demo must not leave new files in the checked-out repository
// (the same rule Media/Pictures/SavePicture follows).
inline std::string XactDirectory() {
    return (std::filesystem::temp_directory_path() / "cna-examples-xact").string();
}

inline std::string SettingsPath() { return XactDirectory() + "/Demo.xgs"; }
inline std::string WaveBankPath() { return XactDirectory() + "/Waves.xwb"; }
inline std::string SoundBankPath() { return XactDirectory() + "/Sounds.xsb"; }

// The four cues the banks define. Two categories, so AudioCategory has
// something to act on that is not "everything".
inline constexpr const char* kCueNames[4] = {"Tone1", "Tone2", "Tone3", "Tone4"};
inline constexpr float kCueFrequencies[4] = {261.63f, 329.63f, 392.00f, 523.25f};
inline constexpr const char* kCueCategoryNames[4] = {"Music", "Music", "SFX", "SFX"};

// Generates all three banks. Returns an error string, empty on success, so the
// caller can put a real failure on screen rather than crashing.
inline std::string GenerateXactBanks() {
#if defined(CNA_EXAMPLES_HAS_XACT_FILEGEN)
    try {
        std::error_code ec;
        std::filesystem::create_directories(XactDirectory(), ec);
        if (ec) return "could not create " + XactDirectory() + ": " + ec.message();

        // Four sine waves, one per cue, 0.8s each.
        std::vector<std::vector<std::uint8_t>> waves;
        for (float frequency : kCueFrequencies) {
            waves.push_back(XactFileGen::MakeSineWave(frequency, 0.8f));
        }
        XactFileGen::SaveFile(WaveBankPath(), XactFileGen::MakeXwb("Waves", waves));

        // Two categories (Music, SFX) plus a SpeedOfSound variable.
        XactFileGen::SaveFile(SettingsPath(), XactFileGen::MakeXgs());

        // One cue per wave; category index 0 = Music, 1 = SFX.
        std::vector<XactFileGen::CueDef> cues;
        for (std::uint16_t i = 0; i < 4; ++i) {
            cues.push_back({kCueNames[i], i, static_cast<std::uint8_t>(i < 2 ? 0 : 1)});
        }
        XactFileGen::SaveFile(SoundBankPath(), XactFileGen::MakeXsb("Sounds", "Waves", cues));
        return {};
    } catch (const std::exception& ex) {
        return std::string("bank generation threw: ") + ex.what();
    }
#else
    return "XactFileGen.hpp was not available at build time (../cnanext not present)";
#endif
}

inline bool BanksExist() {
    std::error_code ec;
    return std::filesystem::exists(SettingsPath(), ec) &&
           std::filesystem::exists(WaveBankPath(), ec) &&
           std::filesystem::exists(SoundBankPath(), ec);
}

} // namespace CnaExamples::Demos::Audio::XactDemos
