// SPDX-License-Identifier: MIT
#pragma once

#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <string>
#include <system_error>

#include "CNA/Internal/Media/MediaLibraryPaths.hpp"
#include "Microsoft/Xna/Framework/Media/MediaSourceType.hpp"
#include "Microsoft/Xna/Framework/Media/MediaState.hpp"
#include "System/TimeSpan.hpp"

namespace CnaExamples::Demos::Media {

using Microsoft::Xna::Framework::Media::MediaSourceType;
using Microsoft::Xna::Framework::Media::MediaState;

// Every asset here is fully synthetic, generated by ffmpeg from lavfi sources
// (sine tones / testsrc color bars) -- no third-party audio, video, image or
// metadata is bundled with this app. See plan.md section 8 and
// tools/gen_media_library.sh for the exact generation commands. Paths are
// relative to the working directory the built executable runs from, matching
// where the post-build step copies Content/ (see cmake/ExamplesHelpers.cmake).
inline constexpr const char* kToneAWav = "Content/MediaDemo/tone_a.wav";
inline constexpr const char* kToneBWav = "Content/MediaDemo/tone_b.wav";
inline constexpr const char* kToneCWav = "Content/MediaDemo/tone_c.wav";
inline constexpr const char* kUnsupportedOpus = "Content/MediaDemo/unsupported.opus";
inline constexpr const char* kTestClipMp4 = "Content/MediaDemo/test_clip.mp4";

inline const char* MediaStateName(MediaState state) {
    switch (state) {
        case MediaState::Stopped: return "Stopped";
        case MediaState::Playing: return "Playing";
        case MediaState::Paused:  return "Paused";
    }
    return "?";
}

inline const char* MediaSourceTypeName(MediaSourceType type) {
    switch (type) {
        case MediaSourceType::LocalDevice:      return "LocalDevice";
        case MediaSourceType::WindowsMediaConnect: return "WindowsMediaConnect";
    }
    return "?";
}

// "m:ss.mmm" -- durations here are seconds-scale, so this reads better than
// TimeSpan's own full "d.hh:mm:ss.fffffff" form.
inline std::string FormatDuration(const System::TimeSpan& span) {
    const long long totalMs = (long long)span.getTotalMillisecondsProperty();
    const long long minutes = totalMs / 60000;
    const long long seconds = (totalMs % 60000) / 1000;
    const long long millis  = totalMs % 1000;
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%lld:%02lld.%03lld", minutes, seconds, millis);
    return buf;
}

// ---------------------------------------------------------------------------
// Demo media library
// ---------------------------------------------------------------------------
// MediaLibrary indexes the real per-OS Music/Pictures folders that SDL's
// SDL_GetUserFolder() reports. Pointing the demos at the user's actual music
// collection would make them non-deterministic (and would rummage through
// private files just to show an API), so every MediaLibrary demo redirects the
// roots at the small synthetic library under Content/MediaLibraryDemo/ first.
//
// The redirect uses CNA::Internal::Media::MediaLibraryPaths::Set*RootOverride(),
// which is a NOXNA test hook, NOT part of the XNA 4.0 surface -- real XNA has no
// way to say "index this folder instead". The demos say so on screen rather than
// presenting it as normal API usage, and CatalogAccessScreen lets the user flip
// back to the real OS roots to see what the unredirected API actually returns.

// Absolute paths here are long enough to dominate a line. Anything under the
// working directory is shown relative to it, and a home path is shown with "~",
// so what is left on screen is the part that identifies the file.
inline std::string CompactPath(const std::string& path) {
    std::error_code ec;
    const std::string cwd = std::filesystem::current_path(ec).string();
    if (!ec && !cwd.empty() && path.rfind(cwd, 0) == 0 && path.size() > cwd.size() + 1) {
        return path.substr(cwd.size() + 1);
    }
    if (const char* home = std::getenv("HOME")) {
        const std::string h = home;
        if (!h.empty() && path.rfind(h, 0) == 0) return "~" + path.substr(h.size());
    }
    return path;
}

inline std::string DemoMusicRoot() {
    return std::filesystem::absolute("Content/MediaLibraryDemo/Music").string();
}

inline std::string DemoPictureRoot() {
    return std::filesystem::absolute("Content/MediaLibraryDemo/Pictures").string();
}

// A scratch Pictures root for the one demo that writes: MediaLibrary::SavePicture
// creates a "Saved Pictures" folder under whatever the Pictures root is, so
// pointing it at the bundled Content/ would leave new files inside the checked-out
// repository every time the demo ran. A temp directory keeps that side effect
// where it belongs.
inline std::string ScratchPictureRoot() {
    return (std::filesystem::temp_directory_path() / "cna-examples-picture-demo").string();
}

// Applies the demo roots for as long as it is alive, then restores whatever was
// in effect before -- the same discipline the Input area uses for
// TouchPanel::EnabledGestures, since these overrides are process-global.
class ScopedDemoMediaRoots {
public:
    explicit ScopedDemoMediaRoots(bool useDemoRoots = true) {
        if (useDemoRoots) {
            CNA::Internal::Media::MediaLibraryPaths::SetMusicRootOverride(DemoMusicRoot());
            CNA::Internal::Media::MediaLibraryPaths::SetPictureRootOverride(DemoPictureRoot());
        }
    }

    // Explicit roots, for demos that need somewhere writable (or want to point at
    // only one of the two). An empty string leaves that root unoverridden.
    ScopedDemoMediaRoots(const std::string& musicRoot, const std::string& pictureRoot) {
        CNA::Internal::Media::MediaLibraryPaths::SetMusicRootOverride(musicRoot);
        CNA::Internal::Media::MediaLibraryPaths::SetPictureRootOverride(pictureRoot);
    }

    ~ScopedDemoMediaRoots() {
        CNA::Internal::Media::MediaLibraryPaths::SetMusicRootOverride("");
        CNA::Internal::Media::MediaLibraryPaths::SetPictureRootOverride("");
    }

    ScopedDemoMediaRoots(const ScopedDemoMediaRoots&) = delete;
    ScopedDemoMediaRoots& operator=(const ScopedDemoMediaRoots&) = delete;
};

} // namespace CnaExamples::Demos::Media
