// SPDX-License-Identifier: MIT
#pragma once

#include "Microsoft/Xna/Framework/Media/MediaState.hpp"

namespace CnaExamples::Demos::Media {

using Microsoft::Xna::Framework::Media::MediaState;

// Every asset here is fully synthetic, generated by ffmpeg from lavfi sources
// (sine tones / testsrc color bars) -- no third-party audio or video content
// is bundled with this app. See plan.md section 5.5 for the exact generation
// commands. Paths are relative to the working directory the built executable
// runs from, matching where the post-build step copies Content/ (see
// cmake/ExamplesHelpers.cmake).
inline constexpr const char* kToneAWav = "Content/MediaDemo/tone_a.wav";
inline constexpr const char* kToneBWav = "Content/MediaDemo/tone_b.wav";
inline constexpr const char* kToneCWav = "Content/MediaDemo/tone_c.wav";
inline constexpr const char* kUnsupportedOpus = "Content/MediaDemo/unsupported.opus";
inline constexpr const char* kTestClipMp4 = "Content/MediaDemo/test_clip.mp4";

inline const char* MediaStateName(MediaState state) {
    switch (state) {
        case MediaState::Stopped: return "Stopped";
        case MediaState::Playing: return "Playing";
        case MediaState::Paused:  return "Paused";
    }
    return "?";
}

} // namespace CnaExamples::Demos::Media
