// SPDX-License-Identifier: MIT
#pragma once

#include <string>

#include "Microsoft/Xna/Framework/GamerServices/AvatarRenderer.hpp"
#include "Microsoft/Xna/Framework/Vector3.hpp"

namespace CnaExamples::Demos::Avatars {

using Microsoft::Xna::Framework::Vector3;
using Microsoft::Xna::Framework::GamerServices::AvatarRenderer;

// Phase E: unlike D3's Model Content fixtures (synthesized at runtime, nothing borrowed), the
// Avatars area's real-rendering demos need a real skeleton + skinned mesh parts + baked animation
// clips -- procedurally generated by ../cna's own tools/avatar_builder/ pipeline, which this repo
// has no equivalent of. It is copied from ../cna/examples/demo_avatar/Content into
// Content/AvatarDemo at build time (see cmake/ExamplesHelpers.cmake), guarded on ../cna's
// existence, exactly like the Content area's .xnb fixtures and Audio/XACT's bank generator --
// nothing Ms-PL enters this repository's git history. A missing ../cna checkout makes
// ContentManager::Load throw ContentLoadException ("Cannot open file: ..."), which every screen in
// this area catches and reports on screen rather than crashing.
inline std::string AvatarContentRootDirectory() {
    return "Content/AvatarDemo";
}

// The exact lighting values ../cna's own demo_avatar/AvatarDemo.cpp uses (see that file's own
// comment trail: raised once from 0.05/0.05/0.05 to fight a real EasyGL skinned-shader bug where
// EmissiveColor's folded-in ambient term was multiplied by DiffuseColor a second time, then set
// back down to 0.35 once that shader bug was fixed). AvatarRenderer's Light*/AmbientLightColor
// default to black (matching the real, never-drawing XNA implementation's untouched value-type
// defaults), so a real caller must set these before DrawRealEXT renders anything visible.
inline void ConfigureStandardAvatarLightingEXT(AvatarRenderer& renderer) {
    renderer.setAmbientLightColorProperty(Vector3(0.35f, 0.35f, 0.35f));
    renderer.setLightColorProperty(Vector3(1.0f, 1.0f, 1.0f));
    renderer.setLightDirectionProperty(Vector3(-0.4f, -0.6f, -0.7f));
}

} // namespace CnaExamples::Demos::Avatars
