#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Regenerates Content/MediaLibraryDemo/ -- the small, fully synthetic music and
# picture library the Media area's MediaLibrary demos point CNA at via
# MediaLibraryPaths::SetMusicRootOverride()/SetPictureRootOverride().
#
# Everything here is generated by ffmpeg from lavfi sources (sine/testsrc/color).
# No third-party audio, image or metadata is bundled -- artist/album/genre names
# are invented for this app.
#
# The library is deliberately shaped to exercise every part of CNA's indexer:
#   - 2 artists, 3 albums, 2 genres, 6 songs, 1 .m3u playlist
#   - real Vorbis comments (ARTIST/ALBUM/GENRE/TITLE/TRACKNUMBER), so
#     AudioTagParser has something to parse instead of falling back to filenames
#   - one album with cover.png, one without, so Album::HasArt differs
#   - one .wav song with no tag support at all, so the filename-fallback path shows
#   - a nested picture-album tree plus one loose top-level picture
#
# Usage: tools/gen_media_library.sh   (run from the repo root)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/Content/MediaLibraryDemo"

rm -rf "$OUT"
mkdir -p "$OUT/Music" "$OUT/Pictures"

ff() { ffmpeg -hide_banner -loglevel error -y "$@"; }

# --- Songs -----------------------------------------------------------------
# ogg/vorbis carries real Vorbis comments, which is what AudioTagParser reads.

song() {  # song <path> <freq> <seconds> <title> <artist> <album> <genre> <track>
    local path="$1" freq="$2" secs="$3" title="$4" artist="$5" album="$6" genre="$7" track="$8"
    mkdir -p "$(dirname "$path")"
    ff -f lavfi -i "sine=frequency=$freq:duration=$secs" -ar 44100 -ac 1 -c:a libvorbis -q:a 2 \
       -metadata TITLE="$title" -metadata ARTIST="$artist" -metadata ALBUM="$album" \
       -metadata GENRE="$genre" -metadata TRACKNUMBER="$track" "$path"
}

A1="CNA Demo Ensemble"
A2="Solo Oscillator"

song "$OUT/Music/$A1/Sine Studies/01 - Tone A.ogg" 440 3 "Tone A" "$A1" "Sine Studies" "Test Tones" 1
song "$OUT/Music/$A1/Sine Studies/02 - Tone B.ogg" 554 3 "Tone B" "$A1" "Sine Studies" "Test Tones" 2
song "$OUT/Music/$A1/Sine Studies/03 - Tone C.ogg" 659 4 "Tone C" "$A1" "Sine Studies" "Test Tones" 3
song "$OUT/Music/$A1/Square Waves/01 - Buzz.ogg"   220 2 "Buzz"   "$A1" "Square Waves" "Test Tones" 1
song "$OUT/Music/$A2/Single/01 - Lone Sweep.ogg"   330 5 "Lone Sweep" "$A2" "Single" "Sweeps" 1

# A tagless .wav, so the "no tags -> title falls back to the filename stem" path
# is visible in the demo next to the fully-tagged tracks above.
mkdir -p "$OUT/Music/$A2/Single"
ff -f lavfi -i "sine=frequency=880:duration=2" -ar 44100 -ac 1 -c:a pcm_s16le \
   "$OUT/Music/$A2/Single/02 - Untagged Wav.wav"

# --- Album art -------------------------------------------------------------
# Only "Sine Studies" gets a cover, so Album::HasArt is true for one album and
# false for the other two -- a real difference the demo can point at.
ff -f lavfi -i "color=c=0x2E5C8A:size=256x256:duration=1" -frames:v 1 \
   "$OUT/Music/$A1/Sine Studies/cover.png"

# --- Playlist --------------------------------------------------------------
# Relative paths, which is what real .m3u files use.
cat > "$OUT/Music/Favourites.m3u" <<EOF
#EXTM3U
#EXTINF:3,Tone A
$A1/Sine Studies/01 - Tone A.ogg
#EXTINF:5,Lone Sweep
$A2/Single/01 - Lone Sweep.ogg
#EXTINF:2,Buzz
$A1/Square Waves/01 - Buzz.ogg
EOF

# --- Pictures --------------------------------------------------------------
mkdir -p "$OUT/Pictures/Patterns" "$OUT/Pictures/Colors"

ff -f lavfi -i "testsrc=size=320x240:duration=1"    -frames:v 1 "$OUT/Pictures/Patterns/testsrc.png"
ff -f lavfi -i "smptebars=size=320x240:duration=1"  -frames:v 1 "$OUT/Pictures/Patterns/smptebars.png"
ff -f lavfi -i "color=c=0xC0392B:size=200x200:duration=1" -frames:v 1 "$OUT/Pictures/Colors/red.png"
ff -f lavfi -i "color=c=0x2980B9:size=200x200:duration=1" -frames:v 1 "$OUT/Pictures/Colors/blue.png"
ff -f lavfi -i "color=c=0x27AE60:size=160x160:duration=1" -frames:v 1 "$OUT/Pictures/loose.png"

echo "Generated $OUT"
find "$OUT" -type f | sort | sed "s|$OUT/|  |"
du -sh "$OUT"
